service: autoapi

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  memorySize: 512
  #aws KMS config
  #awsKmsKeyArn: arn:aws:kms:us-east-1:XXXXXX:key/some-hash

  #VPC details
  vpc:
    securityGroupIds:
      - "vpc-e6513a8e"
    subnetIds:
      - "subnet-366da17a"
      - "subnet-23a51c59"
      - "subnet-44bfc22d"
  
  #environment variables
  environment: 
    DB_USERNAME: user
    DB_PASSWORD: pwd
    DB_NAME: dbName
    DB_SCHEMA_NAME: schemaName
    DB_HOST: host
    DB_PORT: port
    DB_DIALECT: dialect
    TABLE_NAME: tableName

  #CORS configuration
  cors:
  origin: '*'
  headers:
    - Content-Type
    - Authorization
    - X-Api-Key
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Methods
  allowCredentials: true
  
plugins:
- serverless-offline

functions:
- ${file(app/api/lambdas/crud/functions.yml)}
